### ISSUE TITLE
is the package limited to erasure channel or can it also handle bsc and awgn?

### ISSUE THREAD

**Issue by qodesign** [chaeger/DensE#1]
Not clear from the matlab code. Some plots seem to indicate that awgn and bsc are also supported.
Also, for BCH, the "t" parameter is usually used to denote the number of correctable **_errors_**;
it seems in the matlab comments that it's used here as the number of correctable **_erasures_**
which is d_min - 1. Can you please clarify.

**Comment by chaeger** [comment]
The code is only for the binary erasure channel (BEC) and not for other channels. In this setting, t denotes the number of correctable erasures.

**Comment by qodesign** [comment]
For BCH codes, in your paper :
 "Miscorrection-free Decoding of Staircase Codes"
  https://ieeexplore.ieee.org/document/8345919
In example 1 : the staircase code uses an extended BCH (n=256,k=239) code; this has dmin=6 and can correct floor((dmin-1)/2)=2 errors. So in the matlab code would "t" be 2 or 5?

For the channel, the matlab code has "waterfall_staircase.m" example. The x-axis is Es/No which would imply (to me) an AWGN channel. How would you interpret the results if the matlab code is for BEC channel only?

**Comment by chaeger** [comment]
Indeed, it should probably be 5 for consistency. The legend implies that this is for idealized decoding (no miscorrections = BEC). Feel free to improve the code!

**Comment by qodesign** [comment]
I'll try...any suggestions on which parts would need to change?
...so the staircase code example is valid for AWGN assuming no miscorrections?
